#!/bin/bash

#git
git config --global user.name "avieira-42"
git config --global user.email "vieiramendesalex@gmail.com"

# update packages
sudo apt update -y
sudo apt update

# clang
sudo apt install clang -y
sudo apt install gcc -y

# make
sudo apt install make -y

# python
sudo apt install python3-setuptools -y

# pipx
sudo apt install pipx -y

# norminette
pipx install norminette -y
pipx ensurepath -y

#sdl
sudo apt update
sudo apt install libsdl2-dev libsdl2-mixer-dev
sudo apt install libsdl2-image-dev libsdl2-ttf-dev

#glad
sudo apt update
sudo apt install libglfw3-dev

# nvim
chmod u+x neovim/nvim-linux-x86_64/bin/nvim
sudo cp -r neovim/nvim-linux-x86_64/bin/nvim /usr/local/bin/nvim

# tmux
sudo apt install tmux -y

# xclip
sudo apt install xclip -y

# curl
sudo apt install curl -y

# zsh
sudo apt install zsh -y
rm -rf ~/.oh-my-zsh
sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

# net-tools
sudo apt install net-tools -y

# ripgrep
sudo apt install ripgrep -y

# super key remaps
# Clear window tiling/moving defaults
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "[]"
# Clear tiling-assistant or any extension shortcuts
gsettings set org.gnome.shell.extensions.tiling-assistant tile-left-half "[]"
gsettings set org.gnome.shell.extensions.tiling-assistant tile-right-half "[]"
gsettings set org.gnome.shell.extensions.tiling-assistant tile-top-half "[]"
gsettings set org.gnome.shell.extensions.tiling-assistant tile-bottom-half "[]"
ggsettings set org.gnome.settings-daemon.plugins.media-keys screensaver "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "[]"
gsettings set org.gnome.desktop.lockdown disable-lock-screen true

sudo apt install wmctrl xdotool -y

# kickstart
git clone https://github.com/nvim-lua/kickstart.nvim.git kickstart

# zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# move dotfiles
cp -r ~/repos/dotfiles/dotfiles/.* ~/

# disable ubuntu docker
cd /usr/share/gnome-shell/extensions/
sudo mv ubuntu-dock@ubuntu.com(,.bak)

# open terminal pallete
vi TerminalPallete

# prompt restart
gnome-session-quit
