#!/bin/bash

# update packages
sudo apt update -y
sudo apt update

# clang
sudo apt install clang -y

# make
sudo apt install make -y

# python
sudo apt install python3-setuptools -y

# pipx
sudo apt install pipx -y

# norminette
pipx install norminette -y
pipx ensurepath -y
# nvim

chmod u+x neovim/nvim-linux-x86_64.appimage
sudo mv neovim/nvim-linux-x86_64.appimage /usr/local/bin/nvim

# tmux
sudo apt install tmux -y

# xclip
sudo apt install xclip -y

# curl
sudo apt install curl -y

# zsh
sudo apt install zsh -y

# net-tools
sudo apt install net-tools -y

# ripgrep
sudo apt install ripgrep

# super key remaps
# Clear window tiling/moving defaults
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "[]"
# Clear tiling-assistant or any extension shortcuts
gsettings set org.gnome.shell.extensions.tiling-assistant tile-left-half "[]"
gsettings set org.gnome.shell.extensions.tiling-assistant tile-right-half "[]"
gsettings set org.gnome.shell.extensions.tiling-assistant tile-top-half "[]"
gsettings set org.gnome.shell.extensions.tiling-assistant tile-bottom-half "[]"
ggsettings set org.gnome.settings-daemon.plugins.media-keys screensaver "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "[]"
gsettings set org.gnome.desktop.lockdown disable-lock-screen true

sudo apt install wmctrl xdotool

# lua
sudo apt install lua5.3 liblua5.3-dev
wget https://luarocks.org/releases/luarocks-3.12.2.tar.gz
tar zxpf luarocks-3.12.2.tar.gz
cd luarocks-3.12.2
./configure && make && sudo make install
sudo luarocks install luasocket
lua
require "socket"

# zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# move dotfiles
cp dotfiles/.tmux.conf ~/ 
cp dotfiles/.zshrc ~/
cp neovim_config/nvim/ ~/

# open terminal pallete
vim TerminalPallete

# prompt restart
gnome-session-quit
